## Word Embedding

In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
### Vocabulary size
voc_size=10000

## One Hot Representation

In [4]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4870, 1933, 495, 6320], [4870, 1933, 495, 3312], [4870, 3336, 495, 5672], [9270, 7418, 8327, 7890, 9091], [9270, 7418, 8327, 7890, 2984], [6962, 4870, 1587, 495, 9799], [3594, 6178, 7900, 7890]]


## Word Embedding

In [5]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4870 1933  495 6320]
 [   0    0    0    0 4870 1933  495 3312]
 [   0    0    0    0 4870 3336  495 5672]
 [   0    0    0 9270 7418 8327 7890 9091]
 [   0    0    0 9270 7418 8327 7890 2984]
 [   0    0    0 6962 4870 1587  495 9799]
 [   0    0    0    0 3594 6178 7900 7890]]


In [7]:
dim = 10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [8]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [9]:
print(model.predict(embedded_docs))

[[[ 4.17638458e-02  1.10191219e-02 -2.70449407e-02  4.52182442e-03
   -4.30338979e-02  2.33381130e-02 -6.15715981e-03 -4.43915501e-02
   -3.72786894e-02 -1.59393549e-02]
  [ 4.17638458e-02  1.10191219e-02 -2.70449407e-02  4.52182442e-03
   -4.30338979e-02  2.33381130e-02 -6.15715981e-03 -4.43915501e-02
   -3.72786894e-02 -1.59393549e-02]
  [ 4.17638458e-02  1.10191219e-02 -2.70449407e-02  4.52182442e-03
   -4.30338979e-02  2.33381130e-02 -6.15715981e-03 -4.43915501e-02
   -3.72786894e-02 -1.59393549e-02]
  [ 4.17638458e-02  1.10191219e-02 -2.70449407e-02  4.52182442e-03
   -4.30338979e-02  2.33381130e-02 -6.15715981e-03 -4.43915501e-02
   -3.72786894e-02 -1.59393549e-02]
  [ 4.79536392e-02  1.29909255e-02  1.51491165e-03  2.77045704e-02
   -1.76278837e-02 -2.10557468e-02  2.48899497e-02  4.00759093e-02
   -1.13322362e-02 -4.98163477e-02]
  [ 2.37927698e-02 -3.65296230e-02 -2.48855352e-02 -4.60147373e-02
   -2.57553216e-02 -1.78815238e-02 -7.15417787e-03  4.59039845e-02
    2.50349157e-

In [10]:
embedded_docs[0]

array([   0,    0,    0,    0, 4870, 1933,  495, 6320])

In [11]:
model.predict(embedded_docs)[0]

array([[ 0.04176385,  0.01101912, -0.02704494,  0.00452182, -0.0430339 ,
         0.02333811, -0.00615716, -0.04439155, -0.03727869, -0.01593935],
       [ 0.04176385,  0.01101912, -0.02704494,  0.00452182, -0.0430339 ,
         0.02333811, -0.00615716, -0.04439155, -0.03727869, -0.01593935],
       [ 0.04176385,  0.01101912, -0.02704494,  0.00452182, -0.0430339 ,
         0.02333811, -0.00615716, -0.04439155, -0.03727869, -0.01593935],
       [ 0.04176385,  0.01101912, -0.02704494,  0.00452182, -0.0430339 ,
         0.02333811, -0.00615716, -0.04439155, -0.03727869, -0.01593935],
       [ 0.04795364,  0.01299093,  0.00151491,  0.02770457, -0.01762788,
        -0.02105575,  0.02488995,  0.04007591, -0.01133224, -0.04981635],
       [ 0.02379277, -0.03652962, -0.02488554, -0.04601474, -0.02575532,
        -0.01788152, -0.00715418,  0.04590398,  0.02503492,  0.01637081],
       [-0.03278568,  0.01756355,  0.02519337,  0.00307477,  0.03894513,
         0.01355002,  0.04904937,  0.02004175